language: java
jdk:
    - openjdk8
addons:
    sonarcloud:
        organization: "StefanAdrianHuma"
        token:
            secure: "fd26abd9957ec751e7965d44ebc523b8fe0de7d5"
script: 
- ant build
- sonar-scanner
