language: java
jdk:
    - openjdk8
addons:
    sonarcloud:
        organization: "stefanadrianhuma"
        token:
            secure: "fabed1cbd7bd7aeec36d1bb67d3a1e588db6663b"
script: 
- ant build
- sonar-scanner
